#!/usr/bin/env python3
"""Render the Pragya stage scripts to markdown for review.

The scripts in ``src/ai/pragya/scripts/`` are the source of truth; this exists
so the review document is generated from them rather than maintained beside
them, because a hand-written copy of a reviewed asset drifts the moment either
side is edited.

Run from ``backend/``:
    poetry run python scripts/render_stage_scripts.py
"""
from __future__ import annotations

import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from src.ai.pragya.scripts import (  # noqa: E402
    DISCOVERY_SCRIPTS,
    GLOBAL_GUARDRAILS,
    StageScript,
)

OUT = (BACKEND_ROOT.parent / "docs" / "product-road-map" / "increment-3"
       / "02a_stage_scripts.md")


def bullets(items: tuple[str, ...], indent: str = "") -> str:
    return "\n".join(f"{indent}- {item}" for item in items)


def render_stage(script: StageScript) -> str:
    out = [
        f"## Stage {script.stage} — {script.name}",
        "",
        f"**Goal.** {script.goal}",
        "",
        f"**Entered when.** {script.entry_condition}",
        "",
        "### Standing instructions",
        "",
        script.system_prompt,
        "",
        "### Opening",
        "",
        "> " + script.opening.replace("\n", "\n> "),
        "",
        "### Must resolve before closing",
        "",
        bullets(script.must_cover),
        "",
    ]

    if script.questions:
        out += ["### Permitted questions", ""]
        for i, q in enumerate(script.questions, 1):
            out += [
                f"**Q{i}. {q.ask}**",
                "",
                f"*Why it earns its place:* {q.why}",
                "",
                f"*Skipped when:* {q.skip_if}",
                "",
            ]
            if q.follow_up:
                out += [f"*Follow-up:* {q.follow_up}", ""]

    if script.guardrails:
        out += ["### Stage guardrails", "", bullets(script.guardrails), ""]
    if script.exit_criteria:
        out += ["### Exit criteria", "", bullets(script.exit_criteria), ""]
    if script.artifacts:
        out += ["### Artifacts written", "",
                bullets(tuple(f"`{a}`" for a in script.artifacts)), ""]
    if script.handoff:
        out += ["### Handoff into the next stage", "", f"> {script.handoff}", ""]

    return "\n".join(out)


def main() -> int:
    parts = [
        "# Increment 3 / PRAGYA — Stage 1–5 Scripts (review copy)",
        "",
        "> **Generated** from `backend/src/ai/pragya/scripts/` by",
        "> `backend/scripts/render_stage_scripts.py`. **Do not edit this file** —",
        "> edit the scripts and re-render, or the two will disagree.",
        ">",
        "> **Status:** ✅ **reviewed and approved by Rahul, 2026-07-22**",
        "> (PRAGYA T4 checkpoint, decision 3 — no script ships unreviewed).",
        "",
        "These are the as-is discovery protocol (functional §4.3), the half of",
        "the nine-stage flow that is conversation rather than mechanism.",
        "Stages 6–9 are unscripted by design: they are driven by the Inc-2",
        "wizard APIs, not by discovery.",
        "",
        "---",
        "",
        "## Rules that apply in every stage",
        "",
        bullets(GLOBAL_GUARDRAILS),
        "",
        "---",
        "",
    ]
    for stage in sorted(DISCOVERY_SCRIPTS):
        parts.append(render_stage(DISCOVERY_SCRIPTS[stage]))
        parts.append("---\n")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(BACKEND_ROOT.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
