from arq import Worker
from arq.connections import RedisSettings
from sqlalchemy import select, update
from sqlalchemy.orm import selectinload
from uuid import UUID, uuid4
from datetime import datetime
from decimal import Decimal
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from src.common.database import AsyncSessionLocal
from src.ai.models import (
    ExecutionRun, HierarchicalEntity, LLMInteractionLog, EntityType,
    RunStatus, Document, DocumentChunk, ToolInteractionLog, HumanApproval
)
from src.ai.schemas import (
    RunStatus as RunStatusEnum, EntityStatus, RelationshipType,
    ReasoningMode, StepType, PlanStep, Planning, LogicGate, ContextPolicy
)
from src.config.service import ConfigService
from src.ai.usage_service import UsageService
from src.billing.credit_service import CreditService
from src.billing.billing_service import BillingService
from src.ai.tool_executor import ToolExecutor
from src.ai.memory_service import MemoryRouter  # S1: Memory
from src.ai.llm_router import LLMRouter        # Model-agnostic LLM dispatch
import src.auth.models
import src.config.models
import asyncio
import json
import re
import copy

# --- Prompt Templates ---

DYNAMIC_PLANNER_PROMPT = """You are an AI planning agent. Given a user goal and available capabilities, generate a structured execution plan.

Output a JSON array of steps in this format:
[
  {
    "step_id": "step_1",
    "order": 1,
    "name": "Step Name",
    "description": "What this step accomplishes",
    "type": "ACTION",  // ACTION | TOOL_CALL | THOUGHT
    "target": {
      "prompt_template": "Template with {{variables}}",
      "tool_id": "tool_name_if_applicable"  
    },
    "required": true
  }
]

Rules:
1. If the goal is ambiguous, create a first step of type "THOUGHT" to ask the user for clarification
2. Break complex tasks into atomic, sequential steps
3. Use available tools when they can help accomplish the goal
4. Each step should have clear success criteria implied in its description
"""

DEFAULT_REVIEW_PROMPT = """You are a quality assurance critic. Review the output of an AI step execution.

Evaluate if the output meets the requirements described in the step description.

Respond with a JSON object:
{
  "passed": true/false,
  "reason": "Explanation of why it passed or failed",
  "suggestion": "If failed, specific suggestion for improvement"
}

Be strict but fair. Minor formatting issues are acceptable if the core task is accomplished.
"""

# ---------------------------------------------------------------------------
# Ph-B: UncertaintySignal — raised by _execute_thought when the LLM explicitly
# signals it needs clarification before proceeding.
# Caught by _execute_step_wrapper: routes to HITL or partial-completion annotation.
# ---------------------------------------------------------------------------

class UncertaintySignal(Exception):
    """
    Raised when the LLM explicitly signals it cannot proceed without
    clarification.  The LLM must include the following JSON block anywhere
    in its response to trigger this path:

        {"needs_clarification": true, "question": "...", "confidence": 0.3}

    Attributes:
        question:      The clarifying question the agent wants to ask.
        confidence:    Estimated confidence in completing the task without input (0–1).
        alternatives:  Optional list of alternative interpretations the LLM suggests.
    """
    def __init__(self, question: str, confidence: float = 0.0, alternatives: list = None):
        super().__init__(question)
        self.question = question
        self.confidence = confidence
        self.alternatives = alternatives or []


# ---------------------------------------------------------------------------
# Ph-A: GoalNode — unit of the goal decomposition tree used by
# RecursiveReasoningEngine (defined at module bottom).
# ---------------------------------------------------------------------------

@dataclass
class GoalNode:
    """
    A single node in the goal decomposition tree.

    Fields:
        goal:         Natural-language description of the sub-goal.
        depth:        Current depth in the tree (0 = root).
        confidence:   LLM self-reported confidence for this goal (0–1).
        parent:       Reference to parent GoalNode (None for root).
        children:     Child GoalNodes generated by `expand_goal()`.
        result:       Final string result once the goal is executed.
        status:       'pending' | 'running' | 'completed' | 'failed'
    """
    goal: str
    depth: int = 0
    confidence: float = 1.0
    parent: Optional['GoalNode'] = field(default=None, repr=False)
    children: List['GoalNode'] = field(default_factory=list)
    result: Optional[str] = None
    status: str = 'pending'

    def is_leaf(self) -> bool:
        return len(self.children) == 0

    def to_dict(self) -> dict:
        return {
            "goal": self.goal,
            "depth": self.depth,
            "confidence": self.confidence,
            "status": self.status,
            "result": self.result,
            "children": [c.to_dict() for c in self.children],
        }

# --- Helper Functions ---

def parse_variables(text: str, variables: dict) -> str:
    """Replaces {{variable}} in text with values from variables dict."""
    if not text:
        return ""
    def replace(match):
        key = match.group(1).strip()
        val = variables
        for k in key.split('.'):
            if isinstance(val, dict):
                val = val.get(k, match.group(0))
            else:
                return match.group(0)
        return str(val)
    return re.sub(r'\{\{(.*?)\}\}', replace, text)


def build_sandwich_prompt(
    identity: str,
    goal: Optional[str] = None,
    tools: Optional[List[Dict]] = None,
    few_shot_examples: Optional[List[Dict[str, str]]] = None,
    context: Optional[str] = None,
    current_task: str = "",
    output_schema: Optional[Dict] = None,
    success_criteria: Optional[List[Dict]] = None,
    allowed_deviations: Optional[Dict] = None,
    execution_constraints: Optional[Dict] = None,
) -> str:
    """
    Build structured prompt using the 'Sandwich Method'.
    
    Layers:
    1. Identity & Role (Who I am)
    2. Goal & Objective (What I'm trying to achieve)
    3. Tools & Capabilities (What I can do)
    4. Few-Shot Examples (How I should behave)
    5. Success Criteria (How output will be judged)
    6. Planning Permissions (Dynamic planning deviations)
    7. Output Format (Required output schema)
    8. Execution Constraints (Cost/tool limits)
    9. Context/History (What happened so far)
    10. Current Task (What I need to do now)
    """
    sections = []
    
    # Layer 1: Identity & Role
    sections.append(f"## Identity & Role\n{identity}")
    
    # Layer 2: Goal & Objective
    if goal:
        sections.append(f"## Goal & Objective\n{goal}")
    
    # Layer 3: Tools & Capabilities
    if tools:
        tool_descriptions = "\n".join([
            f"- **{t['name']}**: {t['description']}" for t in tools
        ])
        sections.append(f"## Available Tools\nYou can use the following tools:\n{tool_descriptions}")
    
    # Layer 4: Few-Shot Examples
    if few_shot_examples:
        example_text = "\n\n".join([
            f"**Scenario**: {ex.get('scenario', ex.get('input', ''))}\n**Response**: {ex.get('ideal_response', ex.get('output', ''))}"
            for ex in few_shot_examples
        ])
        sections.append(f"## Examples of Expected Behavior\n{example_text}")
    
    # Layer 5: Success Criteria
    if success_criteria:
        criteria_lines = "\n".join(
            f"- {sc.get('criterion', sc)} (validated by: {sc.get('validation_type', 'llm_judge')})"
            if isinstance(sc, dict) else f"- {sc}"
            for sc in success_criteria
        )
        sections.append(f"## Success Criteria\nYour output will be evaluated against:\n{criteria_lines}")
    
    # Layer 6: Planning Permissions
    if allowed_deviations:
        perm_lines = []
        if allowed_deviations.get("can_add_steps"):
            perm_lines.append("- You MAY add additional steps if needed")
        if allowed_deviations.get("can_skip_optional_steps"):
            perm_lines.append("- You MAY skip optional steps")
        if allowed_deviations.get("can_reorder_steps"):
            perm_lines.append("- You MAY reorder steps for efficiency")
        if allowed_deviations.get("can_change_tools"):
            perm_lines.append("- You MAY choose different tools than specified")
        if perm_lines:
            sections.append(f"## Planning Permissions\n" + "\n".join(perm_lines))
    
    # Layer 7: Output Format
    if output_schema and output_schema.get("properties"):
        schema_str = json.dumps(output_schema, indent=2)
        sections.append(
            f"## Required Output Format\n"
            f"Your response MUST conform to this JSON schema:\n```json\n{schema_str}\n```"
        )
    
    # Layer 8: Execution Constraints
    if execution_constraints:
        constraint_lines = []
        for key, val in execution_constraints.items():
            constraint_lines.append(f"- {key}: {val}")
        sections.append(f"## Execution Constraints\n" + "\n".join(constraint_lines))
    
    # Layer 9: Context/History
    if context:
        sections.append(f"## Previous Context\n{context}")
    
    # Layer 10: Current Task
    sections.append(f"## Current Task\n{current_task}")
    
    return "\n\n".join(sections)


def filter_context_for_step(
    step: PlanStep, 
    full_context: dict, 
    context_policy: Optional[Dict] = None
) -> dict:
    """
    Filter context based on step's explicit inputs and policy.
    
    Args:
        step: The plan step being executed
        full_context: Full execution context dictionary
        context_policy: Policy configuration from logic_gate
        
    Returns:
        Filtered context dictionary
    """
    if not context_policy:
        return full_context
    
    # Check for explicit input dependencies in step target
    if step.target and hasattr(step.target, 'input_dependencies'):
        deps = step.target.input_dependencies or []
        if deps:
            filtered = {"input": full_context.get("input")}
            for dep in deps:
                if dep in full_context:
                    filtered[dep] = full_context[dep]
            return filtered
    
    # Apply context policy
    policy_type = context_policy.get("type", "FULL")
    
    if policy_type == "LAST_N":
        n = context_policy.get("n", 3)
        keys = list(full_context.keys())
        # Always include 'input' and last N keys
        filtered = {"input": full_context.get("input")} if "input" in full_context else {}
        for k in keys[-n:]:
            filtered[k] = full_context[k]
        return filtered
    
    elif policy_type == "SLIDING_WINDOW":
        max_chars = context_policy.get("max_chars", 4000)
        filtered = {}
        total_chars = 0
        # Include from most recent first
        for k in reversed(list(full_context.keys())):
            v_str = str(full_context[k])
            if total_chars + len(v_str) <= max_chars:
                filtered[k] = full_context[k]
                total_chars += len(v_str)
            else:
                break
        return dict(reversed(list(filtered.items())))
    
    elif policy_type == "EXPLICIT":
        explicit_keys = context_policy.get("explicit_keys", [])
        return {k: full_context[k] for k in explicit_keys if k in full_context}
    
    # FULL - return everything
    return full_context



# ---------------------------------------------------------------------------
# call_llm_unified is replaced by LLMRouter — kept as a compatibility shim
# for any call sites that may still reference it. New code should use LLMRouter
# directly via ExecutionEngine._call_llm / _execute_thought.
# ---------------------------------------------------------------------------
async def call_llm_unified(
    config: Dict[str, Any],
    system_prompt: str,
    user_prompt: str,
    api_key: str,  # ignored — LLMRouter resolves keys from DB
    tools: Optional[List[Dict[str, Any]]] = None,
    few_shot_examples: Optional[List[Dict[str, str]]] = None,
    db=None,
    company_id=None,
) -> dict:
    """
    Compatibility shim. New code should call LLMRouter directly.
    If db and company_id are provided, routes via LLMRouter.
    Otherwise falls back to a minimal error response.
    """
    if db and company_id:
        router = LLMRouter(db=db, company_id=company_id)
        task_type = config.get("task_type", "text_generation")
        resp = await router.call_llm(
            task_type=task_type,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            tools=tools,
            temperature=config.get("temperature", 0.7),
            max_tokens=config.get("max_tokens"),
        )
        return {
            "output": resp.output,
            "function_calls": resp.function_calls,
            "prompt_tokens": resp.prompt_tokens,
            "completion_tokens": resp.completion_tokens,
            "latency_ms": resp.latency_ms,
        }
    raise RuntimeError(
        "call_llm_unified requires db and company_id. Use LLMRouter directly."
    )





# --- Execution Engine ---

class ExecutionEngine:
    def __init__(self, db: AsyncSessionLocal, redis_pool):
        self.db = db
        self.redis = redis_pool
        self.config_service = ConfigService(db)
        self.usage_service = UsageService(db)

    async def _execute_steps_dag(self, run, entity, steps: List[dict], context_state: dict) -> List[dict]:
        """Execute steps respecting dependencies, parallelizing independent ones.

        P1-A: Parallel steps each open their own AsyncSession to avoid
        sharing self.db across concurrent coroutines (which would cause
        PendingRollbackError under SQLAlchemy's asyncio driver).
        The orchestrator-level self.db is retained for status/plan commits.
        """

        # 1. Build Dependency Graph
        step_deps = {s["step_id"]: set() for s in steps}
        step_map = {s["step_id"]: s for s in steps}

        for step in steps:
            s_id = step.get("step_id")
            target = step.get("target", {})
            if target and "input_dependencies" in target:
                for dep in target.get("input_dependencies", []):
                     step_deps[s_id].add(dep)

            prompt = target.get("prompt_template", "")
            vars_needed = re.findall(r'\{\{(.*?)\}\}', prompt)
            for var in vars_needed:
                base_var = var.split('.')[0]
                if base_var in step_map and base_var != s_id:
                    step_deps[s_id].add(base_var)

        completed = set()
        for s in steps:
            if s["step_id"] in context_state and s["step_id"] != "input":
                completed.add(s["step_id"])

        results_map = {}
        print(f"DAG Execution Plan for {len(steps)} steps. Dependencies: {step_deps}")

        while len(completed) < len(steps):
            ready = []
            for s in steps:
                s_id = s["step_id"]
                if s_id not in completed:
                    deps = step_deps[s_id]
                    if deps.issubset(completed) or not deps:
                        ready.append(s)

            if not ready:
                remaining = [s["step_id"] for s in steps if s["step_id"] not in completed]
                print(f"Warning: Circular dependency or stall detected. Remaining: {remaining}. Switching to sequential for remainder.")
                for s in steps:
                    if s["step_id"] not in completed:
                        step_obj = PlanStep(**s)
                        res = await self._execute_step_wrapper(run, entity, step_obj, context_state)
                        results_map[s["step_id"]] = res
                        completed.add(s["step_id"])
                break

            print(f"Executing batch: {[s['name'] for s in ready]}")

            if len(ready) == 1:
                # Single-step batch: run on self.db (no isolation overhead)
                step_obj = PlanStep(**ready[0])
                result = await self._execute_step_wrapper(run, entity, step_obj, context_state)
                results_map[ready[0]["step_id"]] = result
                completed.add(ready[0]["step_id"])
            else:
                # Multi-step parallel batch: each step gets its own AsyncSession.
                # P1-A: This prevents PendingRollbackError when two coroutines
                # share self.db and one fails mid-transaction.
                async def _isolated_step(step_dict: dict) -> dict:
                    async with AsyncSessionLocal() as isolated_db:
                        # Build a lightweight engine clone sharing redis but using isolated_db
                        isolated_engine = ExecutionEngine(isolated_db, self.redis)
                        step_obj = PlanStep(**step_dict)
                        return await isolated_engine._execute_step_wrapper(run, entity, step_obj, context_state)

                tasks = [_isolated_step(s) for s in ready]
                batch_results = await asyncio.gather(*tasks, return_exceptions=True)

                for i, result in enumerate(batch_results):
                    step_id = ready[i]["step_id"]
                    if isinstance(result, Exception):
                        print(f"Step {step_id} failed: {result}")
                        results_map[step_id] = {"error": str(result), "step": ready[i]["name"]}
                        raise result
                    else:
                        results_map[step_id] = result
                        completed.add(step_id)

        return [results_map.get(s["step_id"], {}) for s in steps]

    async def _execute_step_wrapper(self, run, entity, step_obj, context_state):
        """Wrapper to handle execution + review + context update for a single step.

        Ph-B: If the LLM raises UncertaintySignal, the step result is annotated
        with needs_clarification=True instead of crashing the run.
        """
        try:
            step_result = await self._execute_step(run, entity, step_obj, context_state)
        except UncertaintySignal as sig:
            print(f"  UncertaintySignal from step '{step_obj.name}': {sig.question}")
            step_result = {
                "step": step_obj.name,
                "output": f"[Clarification needed] {sig.question}",
                "needs_clarification": True,
                "uncertainty_question": sig.question,
                "uncertainty_confidence": sig.confidence,
                "uncertainty_alternatives": sig.alternatives,
            }

        # Review Mechanism
        if entity.logic_gate and entity.logic_gate.get("review_mechanism", {}).get("enabled"):
            step_result = await self._review_step_output(run, entity, step_obj, step_result)

        # Update Context immediately
        if isinstance(step_result, dict) and "output" in step_result:
            context_state[step_obj.name] = step_result["output"]
            if step_obj.step_id:
                context_state[step_obj.step_id] = step_result["output"]

        return step_result

    # --- Updated execute_run using DAG ---

    async def execute_run(self, run_id: UUID) -> dict:
        # 1. Fetch Run and Entity
        result = await self.db.execute(
            select(ExecutionRun)
            .options(selectinload(ExecutionRun.entity))
            .where(ExecutionRun.id == run_id)
        )
        run = result.scalar_one_or_none()
        if not run:
            raise Exception(f"Run {run_id} not found")

        entity = run.entity
        if not entity:
            raise Exception(f"Entity for run {run_id} not found")

        # 2. Update Status and Initialize Trace
        run.status = RunStatus.RUNNING
        run.started_at = datetime.utcnow()
        if not run.trace_id:
            run.trace_id = run.id
        await self.db.commit()
        
        # Publish Update
        channel = f"execution:{run.id}"
        await self.redis.publish(channel, json.dumps({"status": "RUNNING", "run_id": str(run.id)}))

        try:
            # S1: Retrieve memory context
            memory_router = MemoryRouter(self.db)
            memory_ctx = await memory_router.retrieve(
                entity_id=entity.id,
                user_id=run.user_id,
            )
            # Inject formatted memory into the system prompt context
            context_state = run.input_data or {}
            memory_text = memory_router.format_for_prompt(memory_ctx)
            if memory_text:
                context_state["__memory__"] = memory_text
                
            all_step_results = []
            
            # 3. Plan Generation/Reconciliation
            print(f"--- Starting Execution {run.id} for Entity {entity.name} ---")
            plan = await self._get_reconciled_plan(entity, context_state)
            steps = plan.get("steps", [])
            print(f"Plan reconciled. Steps to execute: {len(steps)}")
            run.dynamic_plan = plan # Store the actual plan used
            await self.db.commit()

            # 4. Execute Plan Steps (DAG)
            # Ph-C: checkpoint_every_n_steps — persist context_state after every N steps
            governance = entity.governance or {}
            checkpoint_every_n = int(governance.get("checkpoint_every_n_steps", 3))

            if self._has_parallel_steps(steps):
                all_step_results = await self._execute_steps_dag(run, entity, steps, context_state)
            else:
                # Sequential fallback with incremental checkpointing
                for step_idx, step in enumerate(steps):
                    # Ph-C: Skip steps already in context_state (resume support)
                    step_obj_check = PlanStep(**step)
                    if step_obj_check.step_id and step_obj_check.step_id in context_state:
                        print(f"  Skipping already-completed step: {step_obj_check.name}")
                        continue

                    step_obj = PlanStep(**step)
                    step_result = await self._execute_step_wrapper(run, entity, step_obj, context_state)
                    all_step_results.append(step_result)

                    # Ph-C: Persist checkpoint every N steps
                    if (step_idx + 1) % checkpoint_every_n == 0:
                        run.context_state = dict(context_state)
                        await self.db.commit()
                        print(f"  Checkpoint persisted after step {step_idx + 1} ({step_obj.name})")

                    if self._should_exit(step_obj, context_state):
                        break

            # 5. Finalize
            run.status = RunStatus.COMPLETED
            # Get output from last step
            last_step_name = steps[-1]["name"] if steps else None
            final_output = context_state.get(last_step_name) if last_step_name else "Success"
            
            run.result_data = {"output": final_output, "steps": all_step_results}
            run.context_state = context_state
            run.completed_at = datetime.utcnow()
            run.execution_time_ms = int((run.completed_at - run.started_at).total_seconds() * 1000)
            
            # S2: Write episodic memory for top-level runs
            await memory_router.write_episodic(run)
            
            await self.db.commit()

            # 6. Billing & Credit Deduction (only for top-level runs, not child invocations)
            total_cost = run.total_cost_usd
            if not run.parent_run_id:
                print(f"Checking billing for top-level run {run.id}. Total cost: {total_cost}")
                # Treat None as 0
                if total_cost is None:
                    total_cost = Decimal("0")
                else:
                    total_cost = Decimal(str(total_cost))
                    
                if total_cost > Decimal("0"):
                    try:
                        # Deduct from credit wallet
                        credit_svc = CreditService(self.db)
                        deductions = await credit_svc.consume(run.company_id, total_cost)
                        print(f"Credits deducted for run {run.id}: {deductions}")
                        
                        # Record billing event for reports
                        billing_svc = BillingService(self.db)
                        await billing_svc.record_billing_event(
                            company_id=run.company_id,
                            base_cost=total_cost,
                            grouping_type="process",
                            grouping_value=entity.name,
                            other_ai_cost=total_cost,
                        )
                        print(f"Billing event recorded for run {run.id}: ${total_cost}")
                    except Exception as billing_err:
                        # Log but don't fail the run if billing fails
                        print(f"Cost Deduction Warning: Billing/credit deduction failed for run {run.id}: {billing_err}")
                else:
                    print(f"Run {run.id} cost is 0, no credits deducted.")

            await self.redis.publish(channel, json.dumps({"status": "COMPLETED", "result": run.result_data}))
            return run.result_data

        except Exception as e:
            run.status = RunStatus.FAILED
            run.error_message = str(e)
            run.completed_at = datetime.utcnow()
            await self.db.commit()
            await self.redis.publish(channel, json.dumps({"status": "FAILED", "error": str(e)}))
            raise e
            
    def _has_parallel_steps(self, steps: List[dict]) -> bool:
        """Check if any steps can run in parallel (heuristic)."""
        # If any step relies on a step that is NOT the immediately preceding one, 
        # OR if multiple steps rely on the same parent.
        # For simplicity, if we have explicit dependencies, we assume DAG is intended.
        for s in steps:
            if s.get("target") and s["target"].get("input_dependencies"):
                return True
        return False

    async def _get_reconciled_plan(self, entity: HierarchicalEntity, input_data: dict) -> dict:
        """Merges static and dynamic plans based on strategy."""
        import copy
        planning = entity.planning or {}
        static_plan = copy.deepcopy(planning.get("static_plan", {})) or {}
        
        if "steps" not in static_plan:
            static_plan["steps"] = []
            
        # Fallback: If no steps and it is a leaf action/skill, add a default step
        if not static_plan["steps"] and entity.type in [EntityType.ACTION, EntityType.SKILL]:
            static_plan["steps"] = [{
                "step_id": "auto_generated",
                "order": 1,
                "name": "Execute",
                "description": f"Executing {entity.name}",
                "type": "ACTION",
                "target": {
                    "prompt_template": entity.description or "Process instruction: {{instruction}}"
                },
                "required": True
            }]

        dynamic_config = planning.get("dynamic_planning", {}) or {}
        
        if not dynamic_config.get("enabled"):
            return static_plan

        # Generate dynamic plan via LLM
        print(f"Generating dynamic plan for {entity.name} with input: {input_data}")
        
        # 1. Prepare planning prompt
        goal = input_data.get("input") or str(input_data)
        context = {
            "entity_name": entity.name,
            "entity_description": entity.description,
            "goal": goal,
            "tools": [t.get("tool_id", t.get("name")) for t in entity.capabilities.get("tools", [])] if entity.capabilities else []
        }
        
        system_prompt = DYNAMIC_PLANNER_PROMPT
        user_prompt = f"Goal: {goal}\n\nAvailable Tools: {context['tools']}\n\nGenerate the execution plan."
        
        # 2. Call Planar LLM
        # Use a reasoning model if available for better planning
        try:
            llm_router = LLMRouter(db=self.db, company_id=entity.company_id)
            
            # Using 'thinking' task_type specifically for dynamic planning
            plan_result_resp = await llm_router.call_llm(
                task_type="thinking",
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                temperature=0.4
            )
            
            # 3. Parse and Validate Plan
            output_text = plan_result_resp.output
            
            
            # Extract JSON list
            json_str = output_text
            if "```json" in output_text:
                json_str = output_text.split("```json")[1].split("```")[0]
            elif "[" in output_text and "]" in output_text:
                json_str = output_text[output_text.find("["):output_text.rfind("]")+1]
                
            steps = json.loads(json_str)
            
            # Validate basic structure
            valid_steps = []
            for i, s in enumerate(steps):
                # Ensure GUID step_ids
                if not s.get("step_id"):
                    s["step_id"] = f"step_{i+1}_{str(uuid4())[:8]}"
                valid_steps.append(s)
                
            return {"steps": valid_steps}
            
        except Exception as e:
            print(f"Dynamic planning failed: {e}. Falling back to static plan.")
            # Add error step or fallback?
            return static_plan

    async def _execute_step(self, run: ExecutionRun, entity: HierarchicalEntity, step: PlanStep, context: dict) -> dict:
        """Routes execution to specific step handler."""
        if step.type == StepType.CHILD_ENTITY_INVOCATION:
            return await self._execute_child_invocation(run, step, context)
        elif step.type == StepType.TOOL_CALL:
            return await self._execute_tool_call(run, entity, step, context)
        elif step.type == StepType.THOUGHT or step.type == StepType.ACTION:
            return await self._execute_thought(run, entity, step, context)
        return {"error": "Unknown step type"}

    async def _execute_child_invocation(self, run: ExecutionRun, step: PlanStep, context: dict) -> dict:
        entity_id = step.target.entity_id if step.target else None
        if not entity_id:
            raise Exception(f"Child invocation missing entity_id for step {step.name}")
        
        # Create Child Run
        child_run = ExecutionRun(
            company_id=run.company_id,
            user_id=run.user_id,
            entity_id=step.target.entity_id,
            parent_run_id=run.id,
            trace_id=run.trace_id,
            input_data=context,
            status=RunStatus.PENDING
        )
        self.db.add(child_run)
        await self.db.commit()
        await self.db.refresh(child_run)
        
        # Recursive Execute
        child_result = await self.execute_run(child_run.id)
        
        # rollup metrics
        run.total_cost_usd += child_run.total_cost_usd or 0
        run.total_tokens += child_run.total_tokens or 0
        await self.db.commit()
        
        return {"step": step.name, "output": child_result.get("output"), "child_run_id": str(child_run.id)}

    async def _execute_tool_call(self, run: ExecutionRun, entity: HierarchicalEntity, step: PlanStep, context: dict) -> dict:
        tool_id = step.target.tool_id if step.target else None
        if not tool_id:
            raise Exception(f"Tool call missing tool_id for step {step.name}")
        
        start_time = datetime.utcnow()
        try:
            # Prepare inputs from context/variables
            raw_input = context.get("input") or str(context) # Fallback
            
            extra_context = {
                **context,
                "company_id": str(run.company_id),
                "user_id": str(run.user_id) if run.user_id else "default"
            }
                
            result = await ToolExecutor.execute_tools([{"tool": tool_id, "input": raw_input}], extra_context=extra_context)
            tool_result = result[0]
            
            latency = int((datetime.utcnow() - start_time).total_seconds() * 1000)
            
            # Log Tool Call
            log = ToolInteractionLog(
                run_id=run.id,
                tool_id=tool_id,
                tool_name=tool_id,
                input_parameters={"input": raw_input},
                output_result=tool_result,
                success=tool_result.get("success", False),
                latency_ms=latency
            )
            self.db.add(log)

            # ── Track tool cost in run.total_cost_usd ────────────────────────────
            # Look up cost for this tool from integration registry (service_sku == tool_id,
            # or service_category == 'CUSTOM_API'). One API call counts as qty=1.
            try:
                from src.config.models import IntegrationRegistry as _IR
                from sqlalchemy import select as _sel, or_ as _or
                from decimal import Decimal as _Dec
                _ir_result = await self.db.execute(
                    _sel(_IR).where(
                        _IR.company_id == run.company_id,
                        _or(
                            _IR.service_sku == tool_id,
                            _IR.service_category == "CUSTOM_API",
                        ),
                        _IR.status == "active",
                    ).limit(1)
                )
                _ir_entry = _ir_result.scalar_one_or_none()
                if _ir_entry and _ir_entry.internal_cost:
                    _tool_cost = _Dec(str(_ir_entry.internal_cost))
                    run.total_cost_usd = (run.total_cost_usd or _Dec("0")) + _tool_cost
                    # Log to usage_logs as well
                    from src.ai.models import UsageLog as _UL
                    self.db.add(_UL(
                        company_id=run.company_id,
                        run_id=run.id,
                        sku_id=_ir_entry.id,
                        raw_quantity=_Dec("1"),
                        calculated_cost=_tool_cost,
                        log_metadata={"tool": tool_id, "latency_ms": latency},
                    ))
            except Exception as _ce:
                print(f"Warning: Could not log tool cost for '{tool_id}': {_ce}")
            # ─────────────────────────────────────────────────────────────────────

            await self.db.commit()
            
            return {"step": step.name, "output": tool_result.get("output")}
        except Exception as e:
            return {"step": step.name, "error": str(e), "success": False}

    async def _execute_thought(self, run: ExecutionRun, entity: HierarchicalEntity, step: PlanStep, context: dict) -> dict:
        """Execute a THOUGHT or ACTION step using the model-agnostic LLMRouter."""
        print(f"Executing Thought/Action step: {step.name}")
        logic_gate = entity.logic_gate or {}
        config = logic_gate.get("reasoning_config", {})

        # Resolve task_type from entity config (new model-agnostic field)
        task_type = config.get("task_type", "text_generation")

        # Filter and optionally summarize context
        filtered_context = filter_context_for_step(step, context, logic_gate.get("context_policy"))
        filtered_context = await self._maybe_summarize_context(run, entity, filtered_context)

        # --- Extract identity fields ---
        identity = entity.identity or {}
        system_prompt = identity.get("system_prompt", "You are a helpful assistant.")
        if "persona" in identity:
            system_prompt = identity.get("persona", {}).get("system_prompt", system_prompt)

        few_shot_examples = identity.get("few_shot_examples", [])
        if "persona" in identity:
            few_shot_examples = identity.get("persona", {}).get("few_shot_examples", few_shot_examples)

        # --- Extract architecture fields for prompt ---
        entity_goal = entity.goal or ""
        io_contract = entity.io_contract or {}
        output_schema = io_contract.get("output_schema")
        review_config = logic_gate.get("review_mechanism", {})
        success_criteria = review_config.get("success_criteria") if review_config.get("enabled") else None
        planning = entity.planning or {}
        dynamic_config = planning.get("dynamic_planning", {})
        allowed_deviations = dynamic_config.get("allowed_deviations") if dynamic_config.get("enabled") else None
        governance = entity.governance or {}

        # Build execution constraints dict
        exec_constraints = {}
        exec_limits = governance.get("execution_limits", {})
        max_tool_calls = exec_limits.get("max_tool_calls")
        if max_tool_calls:
            used = sum(context.get('tool_call_counts', {}).values())
            exec_constraints["Tool calls remaining"] = f"{max_tool_calls - used} of {max_tool_calls}"
        max_cost = governance.get("max_cost_usd")
        if max_cost:
            current_cost = float(run.total_cost_usd or 0)
            exec_constraints["Cost budget"] = f"${current_cost:.4f} spent of ${max_cost:.2f} max"
        max_depth = governance.get("max_recursion_depth")
        if max_depth:
            exec_constraints["Max recursion depth"] = str(max_depth)

        # --- Build tools ---
        tool_ids = []
        tool_schemas = []
        if entity.capabilities and entity.capabilities.get("tools"):
            tool_ids = [t.get("tool_id") for t in entity.capabilities.get("tools", [])]
            tool_schemas = ToolExecutor.get_tool_schemas(tool_ids)

        # --- Build sandwich system prompt with all architecture fields ---
        full_system_prompt = build_sandwich_prompt(
            identity=system_prompt,
            goal=entity_goal,
            tools=tool_schemas,
            few_shot_examples=few_shot_examples,
            context=None,
            current_task="",
            output_schema=output_schema,
            success_criteria=success_criteria,
            allowed_deviations=allowed_deviations,
            execution_constraints=exec_constraints if exec_constraints else None,
        )

        # --- Resolve reasoning mode and dispatch ---
        reasoning_mode = config.get("reasoning_mode", "REACT")

        input_vars = {**filtered_context}
        user_prompt = step.target.prompt_template if step.target and step.target.prompt_template else "{{input}}"
        user_prompt = parse_variables(user_prompt, input_vars)

        print(f"  Routing via LLMRouter → task_type={task_type}, reasoning_mode={reasoning_mode}")

        # Common tool executor setup
        extra_context = {
            **filtered_context,
            "company_id": str(run.company_id),
            "user_id": str(run.user_id) if run.user_id else "default",
        }
        if 'tool_call_counts' not in context:
            context['tool_call_counts'] = {}

        all_tool_results = []

        async def _execute_tools(function_calls: list) -> list:
            """Adapter: called by LLMRouter's REACT loop per tool-call turn."""
            results = []
            for fc in function_calls:
                _tr_list = await ToolExecutor.execute_from_function_calls(
                    [fc],
                    extra_context=extra_context,
                    call_counts=context.get('tool_call_counts', {}),
                )
                for _tr in _tr_list:
                    self.db.add(ToolInteractionLog(
                        run_id=run.id,
                        tool_id=_tr.tool,
                        tool_name=_tr.tool,
                        input_parameters=_tr.args,
                        output_result=str(_tr.output),
                        success=_tr.success,
                        latency_ms=_tr.latency_ms,
                    ))
                    all_tool_results.append(_tr.to_dict())
                    results.append({"tool": _tr.tool, "output": _tr.output, "success": _tr.success})
            return results

        llm_router = LLMRouter(db=self.db, company_id=run.company_id)

        # ═══════════════════════════════════════════════════════════════════
        # Reasoning Mode Dispatch
        # ═══════════════════════════════════════════════════════════════════
        if reasoning_mode == "CHAIN_OF_THOUGHT":
            output, response = await self._execute_chain_of_thought(
                llm_router, full_system_prompt, user_prompt, task_type,
                config, tool_schemas, _execute_tools
            )
        elif reasoning_mode == "REFLECTION":
            output, response = await self._execute_reflection(
                llm_router, full_system_prompt, user_prompt, task_type,
                config, tool_schemas, _execute_tools
            )
        elif reasoning_mode == "TREE_OF_THOUGHTS":
            output, response = await self._execute_tree_of_thoughts(
                llm_router, full_system_prompt, user_prompt, task_type,
                config, tool_schemas, _execute_tools
            )
        else:
            # Default: REACT mode (tool-calling loop)
            response = await llm_router.call_llm_react(
                task_type=task_type,
                system_prompt=full_system_prompt,
                user_prompt=user_prompt,
                tool_schemas=tool_schemas,
                execute_tool_fn=_execute_tools,
                temperature=config.get("temperature", 0.7),
                max_tokens=config.get("max_tokens"),
                max_react_turns=12,
            )
            output = response.output

        # If tools ran but LLM gave no final summary, format results
        if all_tool_results and not output.strip():
            output = ToolExecutor.format_tool_results(all_tool_results)

        # Detect UncertaintySignal from LLM output
        if output and '"needs_clarification": true' in output.lower():
            try:
                _parsed = json.loads(output)
                if _parsed.get("needs_clarification"):
                    raise UncertaintySignal(
                        question=_parsed.get("question", "Uncertain about how to proceed."),
                        confidence=_parsed.get("confidence", 0.0),
                        alternatives=_parsed.get("alternatives", []),
                    )
            except json.JSONDecodeError:
                pass

        print(f"  {reasoning_mode} complete. Tokens: {response.prompt_tokens}+{response.completion_tokens}, latency: {response.latency_ms}ms")

        # Log the interaction
        log = LLMInteractionLog(
            run_id=run.id,
            model_provider=response.provider,
            model_name=response.model_name,
            input_prompt=f"System: {full_system_prompt[:500]}\nUser: {user_prompt[:500]}",
            output_response=output,
            prompt_tokens=response.prompt_tokens,
            completion_tokens=response.completion_tokens,
            latency_ms=response.latency_ms,
            reasoning_mode=reasoning_mode,
        )
        self.db.add(log)

        await self._log_usage(run, response.model_name, response.prompt_tokens, response.completion_tokens, log)
        await self.db.commit()
        return {"step": step.name, "output": output}

    # ═══════════════════════════════════════════════════════════════════════
    # Reasoning Mode Implementations
    # ═══════════════════════════════════════════════════════════════════════

    async def _execute_chain_of_thought(self, llm_router, system_prompt, user_prompt,
                                         task_type, config, tool_schemas, execute_tool_fn):
        """CHAIN_OF_THOUGHT: Structured thinking with explicit reasoning chain extraction."""
        cot_system = system_prompt + """

## Reasoning Instructions
Think through this problem step by step. Structure your response as:

<thinking>
Step 1: [your analysis]
Step 2: [your analysis]
...
</thinking>

<answer>
[Your final answer here]
</answer>"""

        response = await llm_router.call_llm_react(
            task_type=task_type,
            system_prompt=cot_system,
            user_prompt=user_prompt,
            tool_schemas=tool_schemas,
            execute_tool_fn=execute_tool_fn,
            temperature=config.get("temperature", 0.5),
            max_tokens=config.get("max_tokens"),
            max_react_turns=12,
        )

        output = response.output
        # Extract <answer> block if present, otherwise use full output
        answer_match = re.search(r'<answer>(.*?)</answer>', output, re.DOTALL)
        if answer_match:
            output = answer_match.group(1).strip()

        return output, response

    async def _execute_reflection(self, llm_router, system_prompt, user_prompt,
                                   task_type, config, tool_schemas, execute_tool_fn):
        """REFLECTION: Three-phase generate → critique → improve cycle."""
        # Phase 1: Initial generation
        initial_response = await llm_router.call_llm_react(
            task_type=task_type,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            tool_schemas=tool_schemas,
            execute_tool_fn=execute_tool_fn,
            temperature=config.get("temperature", 0.7),
            max_tokens=config.get("max_tokens"),
            max_react_turns=12,
        )
        initial_output = initial_response.output

        # Phase 2: Self-critique
        critique_prompt = (
            "Critically evaluate the following response. Identify specific weaknesses, "
            "logical gaps, factual errors, missing information, or areas that could be improved. "
            "Be constructive and specific.\n\n"
            f"ORIGINAL TASK:\n{user_prompt}\n\n"
            f"RESPONSE TO EVALUATE:\n{initial_output}"
        )
        critique_response = await llm_router.call_llm(
            task_type=task_type,
            system_prompt="You are a rigorous, constructive critic. Find specific weaknesses.",
            user_prompt=critique_prompt,
            temperature=0.3,
            max_tokens=config.get("max_tokens"),
        )

        # Phase 3: Improved version
        improve_prompt = (
            f"Here is the original task, an initial response, and a critique of that response. "
            f"Produce an improved version that addresses all the critique points.\n\n"
            f"ORIGINAL TASK:\n{user_prompt}\n\n"
            f"INITIAL RESPONSE:\n{initial_output}\n\n"
            f"CRITIQUE:\n{critique_response.output}\n\n"
            f"IMPROVED RESPONSE:"
        )
        improved_response = await llm_router.call_llm(
            task_type=task_type,
            system_prompt=system_prompt,
            user_prompt=improve_prompt,
            temperature=config.get("temperature", 0.5),
            max_tokens=config.get("max_tokens"),
        )

        # Aggregate token counts for accurate billing
        total_response = copy.copy(improved_response)
        total_response.prompt_tokens = (
            initial_response.prompt_tokens + critique_response.prompt_tokens + improved_response.prompt_tokens
        )
        total_response.completion_tokens = (
            initial_response.completion_tokens + critique_response.completion_tokens + improved_response.completion_tokens
        )
        total_response.latency_ms = (
            initial_response.latency_ms + critique_response.latency_ms + improved_response.latency_ms
        )

        return improved_response.output, total_response

    async def _execute_tree_of_thoughts(self, llm_router, system_prompt, user_prompt,
                                         task_type, config, tool_schemas, execute_tool_fn):
        """TREE_OF_THOUGHTS: Generate N candidate paths in parallel, score, select best."""
        num_paths = config.get("tot_num_paths", 3)

        # Phase 1: Generate N candidate responses in parallel with higher temperature
        async def _generate_candidate(i):
            return await llm_router.call_llm(
                task_type=task_type,
                system_prompt=system_prompt + f"\n\nGenerate approach #{i+1}. Be creative and thorough.",
                user_prompt=user_prompt,
                temperature=min(config.get("temperature", 0.7) + 0.2, 1.0),
                max_tokens=config.get("max_tokens"),
            )

        candidates = await asyncio.gather(*[_generate_candidate(i) for i in range(num_paths)])

        # Phase 2: Score each candidate
        candidates_text = "\n\n---\n\n".join([
            f"## Candidate {i+1}\n{c.output}" for i, c in enumerate(candidates)
        ])
        scoring_prompt = (
            f"You are evaluating {num_paths} different responses to the same task. "
            f"For each candidate, rate it 1-10 on: accuracy, completeness, clarity, and relevance. "
            f"Then select the BEST candidate number.\n\n"
            f"ORIGINAL TASK:\n{user_prompt}\n\n"
            f"CANDIDATES:\n{candidates_text}\n\n"
            f"Respond with JSON: {{\"scores\": [{{\"candidate\": 1, \"score\": 8, \"reason\": \"...\"}}], "
            f"\"best\": <candidate_number>}}"
        )
        scoring_response = await llm_router.call_llm(
            task_type=task_type,
            system_prompt="You are an impartial evaluator. Select the best response.",
            user_prompt=scoring_prompt,
            temperature=0.2,
            max_tokens=1000,
        )

        # Parse scoring to find best candidate
        best_idx = 0  # Default to first candidate
        try:
            score_text = scoring_response.output
            if "{" in score_text and "}" in score_text:
                json_str = score_text[score_text.find("{"):score_text.rfind("}") + 1]
                parsed = json.loads(json_str)
                best_num = parsed.get("best", 1)
                best_idx = max(0, min(best_num - 1, num_paths - 1))
        except (json.JSONDecodeError, ValueError, KeyError):
            pass

        best_output = candidates[best_idx].output

        # Aggregate token counts
        total_prompt = sum(c.prompt_tokens for c in candidates) + scoring_response.prompt_tokens
        total_completion = sum(c.completion_tokens for c in candidates) + scoring_response.completion_tokens
        total_latency = max(c.latency_ms for c in candidates) + scoring_response.latency_ms  # parallel, so max

        total_response = copy.copy(candidates[best_idx])
        total_response.prompt_tokens = total_prompt
        total_response.completion_tokens = total_completion
        total_response.latency_ms = total_latency

        return best_output, total_response

    async def _get_api_key(self, run, config):
        """
        Deprecated — API key resolution is now handled by LLMRouter via
        ConfigService.resolve_model_for_task(). Kept for any remaining call sites.
        """
        task_type = config.get("task_type", "text_generation")
        integration, api_key = await self.config_service.resolve_model_for_task(
            company_id=run.company_id,
            task_type=task_type,
        )
        if not api_key:
            raise Exception(f"API Key not found for task_type='{task_type}'")
        return api_key

    async def _log_usage(self, run, model_name: str, prompt_tokens: int, completion_tokens: int, log):
        """Helper to log LLM usage stats using model_name from LLMResponse."""
        input_sku = f"{model_name}-in" if model_name else "unknown-in"
        output_sku = f"{model_name}-out" if model_name else "unknown-out"

        input_usage = await self.usage_service.log_usage(
            company_id=run.company_id,
            service_sku=input_sku,
            raw_quantity=float(prompt_tokens),
            execution_id=run.id
        )

        output_usage = await self.usage_service.log_usage(
            company_id=run.company_id,
            service_sku=output_sku,
            raw_quantity=float(completion_tokens),
            execution_id=run.id
        )

        if input_usage:
            log.cost_usd += input_usage.calculated_cost
            run.total_cost_usd += input_usage.calculated_cost

        if output_usage:
            log.cost_usd += output_usage.calculated_cost
            run.total_cost_usd += output_usage.calculated_cost

        run.total_tokens += (prompt_tokens + completion_tokens)

    async def _maybe_summarize_context(self, run, entity, context_state: dict) -> dict:
        """Smartly trim context if it exceeds threshold, preserving critical keys."""
        if not entity.logic_gate:
            return context_state

        context_policy = entity.logic_gate.get("context_policy", {})
        threshold = context_policy.get("summarize_threshold", 20000)

        context_str = json.dumps(context_state, default=str)
        if len(context_str) <= threshold:
            return context_state

        print(f"Context size {len(context_str)} exceeds threshold {threshold}. Smart-trimming...")

        always_keep = {"input"}
        explicit_preserve = set(context_policy.get("preserve_keys", []))
        always_keep |= explicit_preserve

        all_keys = list(context_state.keys())
        step_keys = [k for k in all_keys if k not in always_keep]
        recent_keys = set(step_keys[-3:]) if step_keys else set()

        trimmed = {k: context_state[k] for k in all_keys if k in always_keep or k in recent_keys}

        trimmed_str = json.dumps(trimmed, default=str)
        if len(trimmed_str) <= threshold:
            print(f"  Smart-trim reduced context to {len(trimmed_str)} chars.")
            return trimmed

        old_keys = [k for k in step_keys if k not in recent_keys]
        if old_keys:
            old_context_str = json.dumps(
                {k: context_state[k] for k in old_keys}, default=str
            )
            try:
                llm_router = LLMRouter(db=self.db, company_id=run.company_id)
                summary_resp = await llm_router.call_llm(
                    task_type="text_generation",
                    system_prompt=(
                        "Summarise the following execution context into 2-3 concise sentences. "
                        "Preserve any specific names, numbers, facts, or JSON structures mentioned."
                    ),
                    user_prompt=old_context_str,
                    temperature=0.3,
                    max_tokens=800,
                )
                trimmed["earlier_context_summary"] = summary_resp.output
            except Exception as e:
                print(f"  Context summarization failed: {e}. Using trimmed context without summary.")

        final_str = json.dumps(trimmed, default=str)
        print(f"  Context trimmed {len(context_str)} -> {len(final_str)} chars.")
        return trimmed

    async def _review_step_output(self, run, entity, step, result) -> dict:
        """Self-critique review mechanism with retry logic."""
        review_config = entity.logic_gate.get("review_mechanism", {})
        if not review_config.get("enabled"):
            return result
        
        # Don't review errors or tools for now
        if "error" in result:
            return result

        max_retries = entity.logic_gate.get("retry_policy", {}).get("max_retries", 3)
        review_prompt = review_config.get("review_prompt") or DEFAULT_REVIEW_PROMPT
        
        # Get independent API key for critic
        # Use entity's reasoning config or LLM config
        config = logic_gate.get("reasoning_config") or {}
        task_type = config.get("task_type", "text_generation")
        
        current_result = result
        
        for attempt in range(max_retries):
            print(f"Running Review/Critic Attempt {attempt+1}/{max_retries} for step {step.name}")
            
            # Call critic LLM
            critic_input = json.dumps({
                "step_description": step.description,
                "step_output": current_result.get("output"),
                "success_criteria": review_config.get("success_criteria", [])
            }, default=str)
            
            llm_router = LLMRouter(db=self.db, company_id=run.company_id)
            critic_resp = await llm_router.call_llm(
                task_type=task_type,
                system_prompt=review_prompt,
                user_prompt=critic_input,
                temperature=0.2,
            )
            critique_text = critic_resp.output
            passed = False
            reason = ""
            suggestion = ""
            
            try:
                # Try to parse JSON output from critic
                if "{" in critique_text and "}" in critique_text:
                    json_str = critique_text[critique_text.find("{"):critique_text.rfind("}")+1]
                    critique_json = json.loads(json_str)
                    passed = critique_json.get("passed", False)
                    reason = critique_json.get("reason", "")
                    suggestion = critique_json.get("suggestion", "")
                else:
                    # Fallback text parsing
                    passed = "passed" in critique_text.lower() and "true" in critique_text.lower()
                    reason = critique_text
            except Exception as e:
                print(f"Failed to parse critique: {e}")
                passed = False
                reason = "Critique parsing failed"

            if passed:
                return current_result
            
            # Retry with feedback if not passed
            if attempt < max_retries - 1:
                feedback = f"\n\nCRITIC FEEDBACK (Previous Attempt Failed): {reason}. Suggestion: {suggestion}\nPlease improve your response based on this."
                
                # Re-execute step context with feedback appended
                # This is a recursive call to _execute_thought but with modified context/prompt handling requires structural change
                # For MVP, we'll just append feedback to the next prompt or return the annotated result
                # Ideally we want to re-run the step.
                
                # Simplified Retry: Re-run the step with feedback in context
                # NOTE: This recursively calls _execute_step's logic
                retry_context = copy.deepcopy(run.context_state or {})
                retry_context["input"] = (retry_context.get("input", "") + feedback)
                
                # We need to know which type of step it was to retry correctly
                if step.type in [StepType.THOUGHT, StepType.ACTION]:
                    current_result = await self._execute_thought(run, entity, step, retry_context)
                elif step.type == StepType.TOOL_CALL:
                    # Tools usually static, maybe just retry?
                    current_result = await self._execute_tool_call(run, entity, step, retry_context)
                    
            else:
                # Handle failure per on_failure policy
                on_failure = review_config.get("on_failure", "RETRY")
                if on_failure == "ESCALATE":
                    current_result["requires_human_review"] = True
                    current_result["review_failure_reason"] = reason
                elif on_failure == "ABORT":
                    raise Exception(f"Step {step.name} failed verification after {max_retries} attempts: {reason}")
        
        return current_result

    def _should_exit(self, step: PlanStep, context: dict) -> bool:
        """Evaluates exit conditions for early termination."""
        for condition in step.exit_conditions:
            # Simplified evaluation
            if "error" in str(context.get(step.name, "")).lower():
                if condition.next_step == 'ESCALATE':
                    return True
        return False

# --- Arq Jobs ---

async def run_execution_recursive(ctx, run_id_str: str):
    run_id = UUID(run_id_str)
    import redis.asyncio as redis
    from src.common.config import settings
    
    redis_pool = redis.from_url(settings.REDIS_URL or "redis://localhost:6379")
    
    async with AsyncSessionLocal() as db:
        engine = ExecutionEngine(db, redis_pool)
        await engine.execute_run(run_id)
    
    await redis_pool.close()

async def process_document(ctx, document_id_str: str, file_content: bytes, file_type: str, filename: str):
    from src.ai.models import Document, DocumentChunk
    import io
    
    document_id = UUID(document_id_str)
    async with AsyncSessionLocal() as db:
        result = await db.execute(select(Document).where(Document.id == document_id))
        document = result.scalar_one_or_none()
        if not document:
            return
            
        try:
            if file_type == "txt":
                text = file_content.decode("utf-8")
            elif file_type == "pdf":
                import PyPDF2
                pdf_reader = PyPDF2.PdfReader(io.BytesIO(file_content))
                text = ""
                for page in pdf_reader.pages:
                    text += page.extract_text() + "\n"
            elif file_type == "docx":
                import docx
                doc = docx.Document(io.BytesIO(file_content))
                text = "\n".join([p.text for p in doc.paragraphs])
            else:
                text = file_content.decode("utf-8", errors="ignore")
                
            chunk_size = 500
            chunks = [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]
            
            model_name = "gemini-embedding-004"
            
            # Build Vertex AI client for embedding
            from src.common.genai_factory import build_vertex_genai_client
            from google.genai import types as _types
            _embed_client = await build_vertex_genai_client(
                db, document.company_id,
                http_options={"api_version": "v1beta"}
            )
            for idx, chunk_text in enumerate(chunks):
                try:
                    embed_response = _embed_client.models.embed_content(
                        model=model_name,
                        contents=chunk_text,
                        config=_types.EmbedContentConfig(task_type="RETRIEVAL_DOCUMENT")
                    )
                    embedding = embed_response.embeddings[0].values
                except Exception as _embed_err:
                    print(f"Embedding error for chunk {idx}: {_embed_err}")
                    continue

                chunk = DocumentChunk(
                    document_id=document.id,
                    chunk_index=str(idx),
                    content=chunk_text,
                    embedding=embedding
                )
                db.add(chunk)
            
            document.upload_status = "completed"
            await db.commit()
            
        except Exception as e:
            document.upload_status = "failed"
            await db.commit()
            print(f"Doc processing failed: {e}")

# Import campaign worker functions
from src.ai.campaign_worker import execute_campaign_task, pause_campaign_task, stop_campaign_task

# ---------------------------------------------------------------------------
# Ph-C: resume_execution — Arq job to resume a checkpointed run
# ---------------------------------------------------------------------------
async def resume_execution(ctx: dict, run_id_str: str) -> dict:
    """
    Resume a previously checkpointed execution run.
    Reloads `run.context_state` and skips steps that are already completed.
    """
    from src.common.database import AsyncSessionLocal
    
    run_id = UUID(run_id_str)
    async with AsyncSessionLocal() as db:
        # We need the redis pool from the Arq context
        redis = ctx.get('redis')
        engine = ExecutionEngine(db, redis)
        print(f"Resuming ExecutionRun: {run_id}")
        return await engine.execute_run(run_id)


# ---------------------------------------------------------------------------
# Ph-A: RecursiveReasoningEngine — extends ExecutionEngine with Goal Trees
# ---------------------------------------------------------------------------
class RecursiveReasoningEngine(ExecutionEngine):
    """
    Experimental engine supporting dynamic goal decomposition (Phase A).
    Instead of a flat DAG of steps, goals are recursively decomposed into
    a tree of sub-goals until the LLM's confidence exceeds a threshold.
    """
    async def execute_tree(self, run: ExecutionRun, root_goal: GoalNode, context: dict) -> str:
        """Evaluate the tree DFS, expanding unconfident nodes."""
        print(f"GoalTree: Executing node: {root_goal.goal} (Depth {root_goal.depth})")
        
        # Base case: execute node if it's confident enough to be a leaf
        if root_goal.is_leaf() and root_goal.confidence >= 0.7:
            result = await self._execute_goal_leaf(run, root_goal, context)
            root_goal.result = result
            root_goal.status = "completed"
            return result
            
        # Recursive case: expand goal into children if it hasn't been yet
        if not root_goal.children:
            await self._expand_goal(root_goal, context)
            
        # Execute children
        child_results = []
        for child in root_goal.children:
            res = await self.execute_tree(run, child, context)
            child_results.append(res)
            
        root_goal.result = "\n".join(child_results)
        root_goal.status = "completed"
        return root_goal.result

    async def _expand_goal(self, node: GoalNode, context: dict) -> None:
        """Call LLM to decompose a complex goal into 2-5 subgoals."""
        prompt = (
            f"Decompose the following complex goal into atomic, sequential subgoals.\n"
            f"Goal: {node.goal}\n"
            f"Current Context: {json.dumps(context)[:1000]}\n\n"
            f"Output JSON array of subgoal strings."
        )
        # Use the generic router for the thinking/decomposition task type
        from .llm_router import LLMRouter
        llm_router = LLMRouter(db=self.db, company_id=self.company_id)
        
        try:
            res = await llm_router.call_llm(
                task_type="thinking",
                system_prompt="You are a goal decomposition expert. Output only JSON array wrapper [\"goal1\", \"goal2\"].",
                user_prompt=prompt,
                temperature=0.4
            )
            subgoals = json.loads(res.output)
            for sg in subgoals:
                node.children.append(GoalNode(goal=sg, depth=node.depth + 1, parent=node, status="pending"))
        except (json.JSONDecodeError, AttributeError):
            print(f"Failed to expand goal: {node.goal}")
            # act as leaf
            pass
            
    async def _execute_goal_leaf(self, run: ExecutionRun, node: GoalNode, context: dict) -> str:
        """Execute a concrete atomic goal via flat engine _execute_step."""
        step = PlanStep(
            step_id=str(uuid4()),
            name=f"leaf_{node.depth}",
            description=node.goal,
            type="THOUGHT",  # defaults to REACT thought
            target={"prompt_template": node.goal}
        )
        res = await self._execute_step(run, run.entity, step, context)
        return res.get("output", "Empty leaf result")


class WorkerSettings:
    functions = [
        run_execution_recursive, 
        process_document,
        execute_campaign_task,
        pause_campaign_task,
        stop_campaign_task,
        resume_execution     # Ph-C: registered Arq job
    ]
    job_timeout = 1800  # 30 minutes for long research tasks
    
    # Parse Redis URL from environment config
    @staticmethod
    def _parse_redis_url():
        from src.common.config import settings
        from urllib.parse import urlparse
        parsed = urlparse(settings.REDIS_URL or "redis://localhost:6379")
        return parsed.hostname or "localhost", parsed.port or 6379
    
    _host, _port = _parse_redis_url.__func__()
    redis_settings = RedisSettings(host=_host, port=_port)

