import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { WEATHER_STATES, asWeatherState } from "../src/api/estate";
import { firstMeasurableOn, type KpiHistory } from "../src/api/gallery";
import { flagState, type FeatureFlagView } from "../src/api/undercroft";

/**
 * R-4 part P — the thirteen wrappers, and the gate that makes a wrong path
 * fail here instead of in a browser.
 *
 * The finding this file answers: `src/fixtures/undercroft.ts` names an endpoint
 * per bay and asserts in prose that each one "answers today". Three of those
 * strings were wrong and a fourth named a router that did not exist — on the
 * one surface whose whole job is to be checkable. Nothing in the tree compared
 * a path the client calls against a path the server serves, so the wrongness
 * survived a full workstream.
 *
 * `openapi.json` is the server's own description of itself, regenerated by
 * `npm run gen:api`. Comparing against it is the cheapest cross-language gate
 * available: a renamed endpoint, a dropped router or a typo turns this red in
 * the same commit range as the change.
 */

const SRC_API = path.resolve(__dirname, "..", "src", "api");
const SPEC = path.join(SRC_API, "openapi.json");
const UNDERCROFT_FIXTURE = path.resolve(
  __dirname, "..", "src", "fixtures", "undercroft.ts",
);
const ESTATE_MODULE = path.resolve(
  __dirname, "..", "..", "backend", "src", "ai", "genui", "estate.py",
);

/** `{process_code}` and `{id}` are the same shape of hole. */
function normalise(route: string): string {
  return route.replace(/\{[^}]*\}/g, "{}");
}

interface Call {
  module: string;
  method: string;
  route: string;
}

/**
 * Every `api.<verb>(<literal>)` call under `src/api/`, with template holes
 * flattened. Deliberately a scan rather than a registry the wrappers import:
 * a registry is a second place to be wrong, and a wrapper that forgot to
 * register would be invisible to exactly the check that is supposed to find it.
 */
function callsInClient(): Call[] {
  const calls: Call[] = [];
  const pattern =
    /api\.(get|post|put|patch|delete)(?:<[\s\S]*?>)?\(\s*(`[^`]*`|"[^"]*")/g;
  for (const file of readdirSync(SRC_API).filter((f) => f.endsWith(".ts"))) {
    const source = readFileSync(path.join(SRC_API, file), "utf8");
    for (const match of source.matchAll(pattern)) {
      const verb = match[1];
      const literal = match[2];
      if (verb === undefined || literal === undefined) continue;
      calls.push({
        module: file,
        method: verb.toUpperCase(),
        route: normalise(literal.slice(1, -1).replace(/\$\{[^}]*\}/g, "{}")),
      });
    }
  }
  return calls;
}

function servedRoutes(): Set<string> {
  const spec = JSON.parse(readFileSync(SPEC, "utf8")) as {
    paths: Record<string, Record<string, unknown>>;
  };
  const served = new Set<string>();
  for (const [route, operations] of Object.entries(spec.paths)) {
    for (const method of Object.keys(operations)) {
      if (!["get", "post", "put", "patch", "delete"].includes(method)) continue;
      served.add(`${method.toUpperCase()} ${normalise(route)}`);
    }
  }
  return served;
}

/** The client mounts at `/api/v1`; two calls override `baseURL` to `/api`. */
function isServed(served: Set<string>, call: Call): boolean {
  return (
    served.has(`${call.method} /api/v1${call.route}`) ||
    served.has(`${call.method} /api${call.route}`)
  );
}

describe("every path the client calls is a path the server serves", () => {
  it("finds calls at all (the scan itself is load-bearing)", () => {
    // A regex that silently stops matching would make every assertion below
    // pass vacuously, which is the failure mode of a scan-based gate.
    expect(callsInClient().length).toBeGreaterThan(60);
  });

  it("resolves each one against openapi.json", () => {
    const served = servedRoutes();
    const missing = callsInClient()
      .filter((call) => !isServed(served, call))
      .map((call) => `${call.module}: ${call.method} ${call.route}`);
    expect(missing).toEqual([]);
  });

  /**
   * `genui.fetchTrays()` and `trays.fetchTrayList()` both read
   * `/ai/genui/trays`; whichever a surface happened to import decided whether
   * it received the composed tray or an array of `unknown`. R-4 §7 deletes the
   * weaker one. The general rule is that one path has one wrapper — the two
   * standing exceptions are named here with their reasons, so a *new*
   * duplicate is what turns this red.
   */
  it("has one wrapper per path, but for two named exceptions", () => {
    const modulesByRoute = new Map<string, Set<string>>();
    for (const call of callsInClient()) {
      const key = `${call.method} ${call.route}`;
      const modules = modulesByRoute.get(key) ?? new Set<string>();
      modules.add(call.module);
      modulesByRoute.set(key, modules);
    }
    const shared = [...modulesByRoute.entries()]
      .filter(([, modules]) => modules.size > 1)
      .map(([route]) => route)
      .sort();
    expect(shared).toEqual([
      // Three different reads of one bus: the raw list for the Undercroft, and
      // two domain projections (record proposals, sync conflicts) that filter
      // it by signal type and reshape the payload.
      "GET /ai/signals",
      // `study.fetchMe` is the identity itself; `identity.fetchCompanyName`
      // reads it only to learn which company to look up, and fails soft.
      "GET /auth/me",
    ]);
  });

  it("no longer exports the duplicate tray read", async () => {
    const genui = await import("../src/api/genui");
    expect(Object.keys(genui)).not.toContain("fetchTrays");
  });
});

/**
 * The four `source` strings the Undercroft got wrong, and what they should
 * say. Encoded as data so the correction is auditable and so it *expires*: if
 * the backend ever grows `/ai/flags` for real, the second assertion fails and
 * the table gets re-read rather than trusted.
 */
const CORRECTIONS: { wrong: string; right: string }[] = [
  { wrong: "/ai/tenant-schema/defs", right: "/ai/tenant/defs" },
  { wrong: "/ai/intelligence/routing", right: "/ai/intelligence/routing-decisions" },
  { wrong: "/ai/flags", right: "/ai/admin/feature_flags/me" },
];

describe("the Undercroft's endpoint claims (D6 §15)", () => {
  it("names, for each wrong path, a real one that replaces it", () => {
    const served = servedRoutes();
    for (const { right } of CORRECTIONS) {
      expect(served, `${right} must be served`).toContain(`GET /api/v1${right}`);
    }
  });

  it("keeps the superseded paths unserved, so the table cannot go stale", () => {
    const served = servedRoutes();
    for (const { wrong } of CORRECTIONS) {
      expect(served, `${wrong} is served now — recheck the correction table`)
        .not.toContain(`GET /api/v1${wrong}`);
    }
  });

  /**
   * `/ai/consent` is the fourth. It is the one the fixture guessed *right* by
   * accident: nothing served it (the tables, the registry and migration
   * `trust001` all shipped behind no router) until D8's E1 built the door at
   * exactly that path. So the bay's claim is true now, and this pins it.
   */
  it("has the consent bay's endpoint, which D8 E1 built", () => {
    expect(servedRoutes()).toContain("GET /api/v1/ai/consent");
  });

  /**
   * The fixture belongs to another family this round, so this does not demand
   * it be correct — it demands that any path in it is either served or one of
   * the three known-wrong strings above. A *new* bay with an invented endpoint
   * fails here.
   */
  it("lets no unaccounted-for endpoint into the bay list", () => {
    const served = servedRoutes();
    const known = new Set(CORRECTIONS.map((c) => c.wrong));
    const fixture = readFileSync(UNDERCROFT_FIXTURE, "utf8");
    const claimed = [...fixture.matchAll(/source:\s*"(GET|POST) ([^"]+)"/g)];
    expect(claimed.length).toBeGreaterThan(0);
    const unaccounted = claimed
      .map(([, method, route]) => ({ method, route }))
      .filter(
        ({ method, route }) =>
          route !== undefined &&
          !known.has(route) &&
          !served.has(`${method} /api/v1${normalise(route)}`),
      )
      .map(({ method, route }) => `${method} ${route}`);
    expect(unaccounted).toEqual([]);
  });
});

/**
 * The district shape reconcile (R-4 §8).
 *
 * The prototype fixture's weather union carried `fog`, `busy` and `frost`. The
 * backend emits four states and says in its own docstring that fog is a
 * **named absence** — D5 §2.1 derives it from "the KPI has been below target
 * for N snapshots" and `KpiDefinition` declares neither a target nor a
 * direction, so there is nothing to be below.
 *
 * The reconcile went the fixture's way, and this is the gate on that decision:
 * the client's vocabulary is read out of the server's own source. If the KPI
 * registry grows a target and `weather_for` starts emitting fog, this goes red
 * on the commit that adds it rather than on the day someone notices the state
 * never appears.
 */
describe("the district's weather vocabulary is the backend's", () => {
  it("matches every state `weather_for` can return", () => {
    const module = readFileSync(ESTATE_MODULE, "utf8");
    const start = module.indexOf("def weather_for(");
    const end = module.indexOf("def envelope_days_left(", start);
    expect(start, "weather_for must be findable in estate.py").toBeGreaterThan(-1);
    expect(end).toBeGreaterThan(start);
    const emitted = [
      ...module.slice(start, end).matchAll(/"state":\s*"([a-z-]+)"/g),
    ].map((match) => match[1]);
    expect(new Set(emitted)).toEqual(new Set(WEATHER_STATES));
  });

  it("does not carry the three states nothing emits", () => {
    for (const absent of ["fog", "busy", "frost"]) {
      expect(WEATHER_STATES as readonly string[]).not.toContain(absent);
    }
  });

  it("reads an unknown weather word as an absence, never as calm", () => {
    // The one direction this must never guess in: falling back to `clear`
    // would report calm the server never sent.
    expect(asWeatherState("fog")).toBeNull();
    expect(asWeatherState(undefined)).toBeNull();
    expect(asWeatherState("storm")).toBe("storm");
  });
});

describe("derivations that would otherwise be re-invented per caller", () => {
  it("reports the earliest measurable day across a set of series", () => {
    const history: KpiHistory = {
      from: "2026-06-01",
      to: "2026-07-31",
      series: [
        {
          key: "dso",
          display_name: "Days sales outstanding",
          unit: "days",
          first_measurable_on: "2026-07-25",
          measurable_days: 6,
          points: [],
        },
        {
          key: "win_rate",
          display_name: "Quote win rate",
          unit: "percent",
          first_measurable_on: null,
          measurable_days: 0,
          points: [],
        },
      ],
    };
    expect(firstMeasurableOn(history)).toBe("2026-07-25");
  });

  it("says nothing rather than a date when no series was ever measurable", () => {
    // The KPI series starts 2026-07-25 with no backfill, by construction. A
    // window before that has no first day, and inventing one would date a
    // record that does not exist.
    const history: KpiHistory = {
      from: "2026-03-01",
      to: "2026-04-01",
      series: [
        {
          key: "dso",
          display_name: "Days sales outstanding",
          unit: "days",
          first_measurable_on: null,
          measurable_days: 0,
          points: [],
        },
      ],
    };
    expect(firstMeasurableOn(history)).toBeNull();
  });

  it("resolves a flag company-override first, then global, then default", () => {
    const view: FeatureFlagView = {
      defaults: { "genui.line.push": true, "sega.tool_synthesis": false },
      numeric_defaults: {},
      overrides: {
        "genui.line.push": { global: false, company: true },
        "sega.tool_synthesis": { global: true },
      },
    };
    expect(flagState(view, "genui.line.push")).toEqual({
      on: true,
      scope: "company",
    });
    expect(flagState(view, "sega.tool_synthesis")).toEqual({
      on: true,
      scope: "global",
    });
  });

  it("distinguishes a flag that is off from a flag nobody has heard of", () => {
    const view: FeatureFlagView = {
      defaults: { "twin.promotion.canary": false },
      numeric_defaults: {},
      overrides: {},
    };
    expect(flagState(view, "twin.promotion.canary")).toEqual({
      on: false,
      scope: "default",
    });
    expect(flagState(view, "fleet.glm.optin")).toBeNull();
  });
});
